FROM golang:1.22.4 AS builder

ARG VERSION=dev
WORKDIR /app

# {{ENV}}
ENV FRONTEND_ORIGIN {FRONTEND_ORIGIN}
ENV MAIL_SERVICE_EMAIL {MAIL_SERVICE_EMAIL}
ENV MAIL_SERVICE_PASSWORD {MAIL_SERVICE_PASSWORD}
ENV 2FACTOR_KEY {2FACTOR_KEY}
ENV REDIRECT_URI {REDIRECT_URI}
ENV CLIENT_ID {CLIENT_ID}
ENV CLIENT_SECRET {CLIENT_SECRET}
ENV DB_CONNECTION_STRING {DB_CONNECTION_STRING}
ENV AUTH_JWT_SECRET {AUTH_JWT_SECRET}
ENV RAZORPAY_KEY_ID {RAZORPAY_KEY_ID}
ENV RAZORPAY_KEY_SECRET {RAZORPAY_KEY_SECRET}
# {{END ENV}}


ENV ENV=production

RUN go install github.com/swaggo/swag/cmd/swag@latest
COPY . .
ENV PATH=$PATH:/go/bin
RUN make build
CMD ["./strive_backend"]